name: Build Windows

on:
  push:
    branches:
      - main # Or your default branch

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: x86_64-pc-windows-gnu
          override: true

      - name: Install MinGW
        run: |
          choco install mingw
          echo "C:\tools\mingw64\bin" >> $env:GITHUB_PATH

      - name: Build
        run: cargo build --release --target x86_64-pc-windows-gnu

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: sitg-video-trimmer-windows.exe
          path: target/x86_64-pc-windows-gnu/release/sitg-video-trimmer.exe
